/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { Activity, SimpleActivity } from '../models/index'
import {
  ActivityFromJSON,
  ActivityToJSON,
  SimpleActivityFromJSON,
  SimpleActivityToJSON,
} from '../models/index'

export interface CreateActivityRequest {
  activity: Activity
}

export interface DeleteActivityRequest {
  activityId: number
}

export interface GetActivitiesRequest {
  date?: Date
  meetingPlace?: string
  page?: number
  size?: number
  sort?: string
}

export interface GetActivityRequest {
  activityId: number
}

export interface InsertActivityRequest {
  activityId: number
  userId: number
}

export interface ShareActivityRequest {
  activityId: number
}

export interface UpdateActivityRequest {
  activityId: number
  activity?: Activity
}

/**
 *
 */
export class ActivityApi extends runtime.BaseAPI {
  /**
   * Create a new activity
   * Create a new activity
   */
  async createActivityRaw(
    requestParameters: CreateActivityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Activity>> {
    if (requestParameters['activity'] == null) {
      throw new runtime.RequiredError(
        'activity',
        'Required parameter "activity" was null or undefined when calling createActivity().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/activities`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ActivityToJSON(requestParameters['activity']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => ActivityFromJSON(jsonValue))
  }

  /**
   * Create a new activity
   * Create a new activity
   */
  async createActivity(
    requestParameters: CreateActivityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Activity> {
    const response = await this.createActivityRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * delete a activity
   * Deletes a activity
   */
  async deleteActivityRaw(
    requestParameters: DeleteActivityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['activityId'] == null) {
      throw new runtime.RequiredError(
        'activityId',
        'Required parameter "activityId" was null or undefined when calling deleteActivity().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/activities/{activityId}`.replace(
          `{${'activityId'}}`,
          encodeURIComponent(String(requestParameters['activityId'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * delete a activity
   * Deletes a activity
   */
  async deleteActivity(
    requestParameters: DeleteActivityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteActivityRaw(requestParameters, initOverrides)
  }

  /**
   * Get all activity filtering by differents fields
   * Get all activity
   */
  async getActivitiesRaw(
    requestParameters: GetActivitiesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<SimpleActivity>>> {
    const queryParameters: any = {}

    if (requestParameters['date'] != null) {
      queryParameters['date'] = (requestParameters['date'] as any).toISOString().substring(0, 10)
    }

    if (requestParameters['meetingPlace'] != null) {
      queryParameters['meetingPlace'] = requestParameters['meetingPlace']
    }

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size']
    }

    if (requestParameters['sort'] != null) {
      queryParameters['sort'] = requestParameters['sort']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/activities`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(SimpleActivityFromJSON),
    )
  }

  /**
   * Get all activity filtering by differents fields
   * Get all activity
   */
  async getActivities(
    requestParameters: GetActivitiesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<SimpleActivity>> {
    const response = await this.getActivitiesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get activity by id
   * Get an activity
   */
  async getActivityRaw(
    requestParameters: GetActivityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Activity>> {
    if (requestParameters['activityId'] == null) {
      throw new runtime.RequiredError(
        'activityId',
        'Required parameter "activityId" was null or undefined when calling getActivity().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/activities/{activityId}`.replace(
          `{${'activityId'}}`,
          encodeURIComponent(String(requestParameters['activityId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => ActivityFromJSON(jsonValue))
  }

  /**
   * Get activity by id
   * Get an activity
   */
  async getActivity(
    requestParameters: GetActivityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Activity> {
    const response = await this.getActivityRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Insert an user on your activity
   * Insert an user on your activity
   */
  async insertActivityRaw(
    requestParameters: InsertActivityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['activityId'] == null) {
      throw new runtime.RequiredError(
        'activityId',
        'Required parameter "activityId" was null or undefined when calling insertActivity().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling insertActivity().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/activities/{activityId}/share/{userId}`
          .replace(`{${'activityId'}}`, encodeURIComponent(String(requestParameters['activityId'])))
          .replace(`{${'userId'}}`, encodeURIComponent(String(requestParameters['userId']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Insert an user on your activity
   * Insert an user on your activity
   */
  async insertActivity(
    requestParameters: InsertActivityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.insertActivityRaw(requestParameters, initOverrides)
  }

  /**
   * Share your activity qr
   * Share your activity qr
   */
  async shareActivityRaw(
    requestParameters: ShareActivityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['activityId'] == null) {
      throw new runtime.RequiredError(
        'activityId',
        'Required parameter "activityId" was null or undefined when calling shareActivity().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/activities/{activityId}/share`.replace(
          `{${'activityId'}}`,
          encodeURIComponent(String(requestParameters['activityId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Share your activity qr
   * Share your activity qr
   */
  async shareActivity(
    requestParameters: ShareActivityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.shareActivityRaw(requestParameters, initOverrides)
  }

  /**
   * Update your activity
   * Update your activity
   */
  async updateActivityRaw(
    requestParameters: UpdateActivityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Activity>> {
    if (requestParameters['activityId'] == null) {
      throw new runtime.RequiredError(
        'activityId',
        'Required parameter "activityId" was null or undefined when calling updateActivity().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/activities/{activityId}`.replace(
          `{${'activityId'}}`,
          encodeURIComponent(String(requestParameters['activityId'])),
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: ActivityToJSON(requestParameters['activity']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => ActivityFromJSON(jsonValue))
  }

  /**
   * Update your activity
   * Update your activity
   */
  async updateActivity(
    requestParameters: UpdateActivityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Activity> {
    const response = await this.updateActivityRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
