/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Ad,
} from '../models/index';
import {
    AdFromJSON,
    AdToJSON,
} from '../models/index';

export interface CreateAdRequest {
    ad: Ad;
}

export interface CreateAdLogRequest {
    body: string;
}

export interface DeleteAdRequest {
    adId: string;
}

export interface GetAdRequest {
    adId: string;
}

export interface GetAdByDateRequest {
    date: string;
}

export interface GetAdsRequest {
    dateFrom?: Date;
    dateUntil?: Date;
    page?: number;
    size?: number;
    sort?: string;
}

export interface UpdateAdRequest {
    adId: string;
    ad?: Ad;
}

/**
 * 
 */
export class AdApi extends runtime.BaseAPI {

    /**
     * Create a new ad
     * Create a new ad
     */
    async createAdRaw(requestParameters: CreateAdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['ad'] == null) {
            throw new runtime.RequiredError(
                'ad',
                'Required parameter "ad" was null or undefined when calling createAd().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/ad`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdToJSON(requestParameters['ad']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new ad
     * Create a new ad
     */
    async createAd(requestParameters: CreateAdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createAdRaw(requestParameters, initOverrides);
    }

    /**
     * Create a new ad log
     * Create a new ad log
     */
    async createAdLogRaw(requestParameters: CreateAdLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createAdLog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/ad/log`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new ad log
     * Create a new ad log
     */
    async createAdLog(requestParameters: CreateAdLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createAdLogRaw(requestParameters, initOverrides);
    }

    /**
     * Delete an ad
     * Delete an ad
     */
    async deleteAdRaw(requestParameters: DeleteAdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['adId'] == null) {
            throw new runtime.RequiredError(
                'adId',
                'Required parameter "adId" was null or undefined when calling deleteAd().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/ad/{adId}`.replace(`{${"adId"}}`, encodeURIComponent(String(requestParameters['adId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an ad
     * Delete an ad
     */
    async deleteAd(requestParameters: DeleteAdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAdRaw(requestParameters, initOverrides);
    }

    /**
     * Get an ad
     * Get an ad
     */
    async getAdRaw(requestParameters: GetAdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ad>> {
        if (requestParameters['adId'] == null) {
            throw new runtime.RequiredError(
                'adId',
                'Required parameter "adId" was null or undefined when calling getAd().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/ad/{adId}`.replace(`{${"adId"}}`, encodeURIComponent(String(requestParameters['adId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdFromJSON(jsonValue));
    }

    /**
     * Get an ad
     * Get an ad
     */
    async getAd(requestParameters: GetAdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ad> {
        const response = await this.getAdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get an ad
     * Get an ad
     */
    async getAdByDateRaw(requestParameters: GetAdByDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ad>> {
        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling getAdByDate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/ad/date`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdFromJSON(jsonValue));
    }

    /**
     * Get an ad
     * Get an ad
     */
    async getAdByDate(requestParameters: GetAdByDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ad> {
        const response = await this.getAdByDateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all ads
     * Get all ads
     */
    async getAdsRaw(requestParameters: GetAdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Ad>>> {
        const queryParameters: any = {};

        if (requestParameters['dateFrom'] != null) {
            queryParameters['dateFrom'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateUntil'] != null) {
            queryParameters['dateUntil'] = (requestParameters['dateUntil'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/ad`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AdFromJSON));
    }

    /**
     * Get all ads
     * Get all ads
     */
    async getAds(requestParameters: GetAdsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Ad>> {
        const response = await this.getAdsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an ad
     * Update an ad
     */
    async updateAdRaw(requestParameters: UpdateAdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ad>> {
        if (requestParameters['adId'] == null) {
            throw new runtime.RequiredError(
                'adId',
                'Required parameter "adId" was null or undefined when calling updateAd().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/ad/{adId}`.replace(`{${"adId"}}`, encodeURIComponent(String(requestParameters['adId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AdToJSON(requestParameters['ad']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdFromJSON(jsonValue));
    }

    /**
     * Update an ad
     * Update an ad
     */
    async updateAd(requestParameters: UpdateAdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ad> {
        const response = await this.updateAdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
