/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { Article, SimpleArticle } from '../models/index'
import {
  ArticleFromJSON,
  ArticleToJSON,
  SimpleArticleFromJSON,
  SimpleArticleToJSON,
} from '../models/index'

export interface CreateArticleRequest {
  article: Article
}

export interface DeleteArticleRequest {
  articleId: number
}

export interface GetArticleByIdRequest {
  articleId: number
}

export interface GetAtriclesRequest {
  title?: string
  location?: string
  organizer?: string
  page?: number
  size?: number
  sort?: string
}

export interface UpdateArticleRequest {
  articleId: number
  article?: Article
}

/**
 *
 */
export class ArticleApi extends runtime.BaseAPI {
  /**
   * Post a nes article
   * Post an article
   */
  async createArticleRaw(
    requestParameters: CreateArticleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['article'] == null) {
      throw new runtime.RequiredError(
        'article',
        'Required parameter "article" was null or undefined when calling createArticle().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/article`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ArticleToJSON(requestParameters['article']),
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Post a nes article
   * Post an article
   */
  async createArticle(
    requestParameters: CreateArticleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.createArticleRaw(requestParameters, initOverrides)
  }

  /**
   * delete an article
   * delete an article
   */
  async deleteArticleRaw(
    requestParameters: DeleteArticleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['articleId'] == null) {
      throw new runtime.RequiredError(
        'articleId',
        'Required parameter "articleId" was null or undefined when calling deleteArticle().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/article/{articleId}`.replace(
          `{${'articleId'}}`,
          encodeURIComponent(String(requestParameters['articleId'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * delete an article
   * delete an article
   */
  async deleteArticle(
    requestParameters: DeleteArticleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteArticleRaw(requestParameters, initOverrides)
  }

  /**
   * Find an article by id
   * Get an article by id
   */
  async getArticleByIdRaw(
    requestParameters: GetArticleByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Article>> {
    if (requestParameters['articleId'] == null) {
      throw new runtime.RequiredError(
        'articleId',
        'Required parameter "articleId" was null or undefined when calling getArticleById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/article/{articleId}`.replace(
          `{${'articleId'}}`,
          encodeURIComponent(String(requestParameters['articleId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => ArticleFromJSON(jsonValue))
  }

  /**
   * Find an article by id
   * Get an article by id
   */
  async getArticleById(
    requestParameters: GetArticleByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Article> {
    const response = await this.getArticleByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Return all articles paginated
   * Get all articles
   */
  async getAtriclesRaw(
    requestParameters: GetAtriclesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<SimpleArticle>>> {
    const queryParameters: any = {}

    if (requestParameters['title'] != null) {
      queryParameters['title'] = requestParameters['title']
    }

    if (requestParameters['location'] != null) {
      queryParameters['location'] = requestParameters['location']
    }

    if (requestParameters['organizer'] != null) {
      queryParameters['organizer'] = requestParameters['organizer']
    }

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size']
    }

    if (requestParameters['sort'] != null) {
      queryParameters['sort'] = requestParameters['sort']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/article`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(SimpleArticleFromJSON),
    )
  }

  /**
   * Return all articles paginated
   * Get all articles
   */
  async getAtricles(
    requestParameters: GetAtriclesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<SimpleArticle>> {
    const response = await this.getAtriclesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * update an article
   * update an article
   */
  async updateArticleRaw(
    requestParameters: UpdateArticleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['articleId'] == null) {
      throw new runtime.RequiredError(
        'articleId',
        'Required parameter "articleId" was null or undefined when calling updateArticle().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (
      this.configuration &&
      (this.configuration.username !== undefined || this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password)
    }
    const response = await this.request(
      {
        path: `/article/{articleId}`.replace(
          `{${'articleId'}}`,
          encodeURIComponent(String(requestParameters['articleId'])),
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: ArticleToJSON(requestParameters['article']),
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * update an article
   * update an article
   */
  async updateArticle(
    requestParameters: UpdateArticleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.updateArticleRaw(requestParameters, initOverrides)
  }
}
