/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ImagesImageDirGet404Response,
} from '../models/index';
import {
    ImagesImageDirGet404ResponseFromJSON,
    ImagesImageDirGet404ResponseToJSON,
} from '../models/index';

export interface ImagesImageDirGetRequest {
    image: string;
    dir: string;
}

export interface PostImageRequest {
    file: Blob;
    name?: string;
    dir?: string;
}

/**
 * 
 */
export class ImageApi extends runtime.BaseAPI {

    /**
     * Recupera una imagen desde el servidor utilizando su ID
     * Obtener una imagen por su nombre
     */
    async imagesImageDirGetRaw(requestParameters: ImagesImageDirGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['image'] == null) {
            throw new runtime.RequiredError(
                'image',
                'Required parameter "image" was null or undefined when calling imagesImageDirGet().'
            );
        }

        if (requestParameters['dir'] == null) {
            throw new runtime.RequiredError(
                'dir',
                'Required parameter "dir" was null or undefined when calling imagesImageDirGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/images/{image}/{dir}`.replace(`{${"image"}}`, encodeURIComponent(String(requestParameters['image']))).replace(`{${"dir"}}`, encodeURIComponent(String(requestParameters['dir']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Recupera una imagen desde el servidor utilizando su ID
     * Obtener una imagen por su nombre
     */
    async imagesImageDirGet(requestParameters: ImagesImageDirGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.imagesImageDirGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Post an image
     * Post an image
     */
    async postImageRaw(requestParameters: PostImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling postImage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['dir'] != null) {
            formParams.append('dir', requestParameters['dir'] as any);
        }

        const response = await this.request({
            path: `/images`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Post an image
     * Post an image
     */
    async postImage(requestParameters: PostImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postImageRaw(requestParameters, initOverrides);
    }

}
