/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ActivityType = {
  Canyon: 'CANYON',
} as const
export type ActivityType = (typeof ActivityType)[keyof typeof ActivityType]

export function instanceOfActivityType(value: any): boolean {
  for (const key in ActivityType) {
    if (Object.prototype.hasOwnProperty.call(ActivityType, key)) {
      if (ActivityType[key as keyof typeof ActivityType] === value) {
        return true
      }
    }
  }
  return false
}

export function ActivityTypeFromJSON(json: any): ActivityType {
  return ActivityTypeFromJSONTyped(json, false)
}

export function ActivityTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityType {
  return json as ActivityType
}

export function ActivityTypeToJSON(value?: ActivityType | null): any {
  return value as any
}

export function ActivityTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ActivityType {
  return value as ActivityType
}
