/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { SimpleUser } from './SimpleUser'
import {
  SimpleUserFromJSON,
  SimpleUserFromJSONTyped,
  SimpleUserToJSON,
  SimpleUserToJSONTyped,
} from './SimpleUser'

/**
 *
 * @export
 * @interface Activity
 */
export interface Activity {
  /**
   *
   * @type {number}
   * @memberof Activity
   */
  activityId?: number
  /**
   *
   * @type {SimpleUser}
   * @memberof Activity
   */
  user?: SimpleUser
  /**
   *
   * @type {Date}
   * @memberof Activity
   */
  date?: Date
  /**
   *
   * @type {string}
   * @memberof Activity
   */
  meetingPlace?: string
  /**
   *
   * @type {string}
   * @memberof Activity
   */
  activityType?: string
  /**
   *
   * @type {number}
   * @memberof Activity
   */
  capacity?: number
  /**
   *
   * @type {string}
   * @memberof Activity
   */
  meetingTime?: string
  /**
   *
   * @type {string}
   * @memberof Activity
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof Activity
   */
  qr?: string
  /**
   *
   * @type {Array<number>}
   * @memberof Activity
   */
  participants?: Array<number>
}

/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value: object): value is Activity {
  return true
}

export function ActivityFromJSON(json: any): Activity {
  return ActivityFromJSONTyped(json, false)
}

export function ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activity {
  if (json == null) {
    return json
  }
  return {
    activityId: json['activityId'] == null ? undefined : json['activityId'],
    user: json['user'] == null ? undefined : SimpleUserFromJSON(json['user']),
    date: json['date'] == null ? undefined : new Date(json['date']),
    meetingPlace: json['meetingPlace'] == null ? undefined : json['meetingPlace'],
    activityType: json['activityType'] == null ? undefined : json['activityType'],
    capacity: json['capacity'] == null ? undefined : json['capacity'],
    meetingTime: json['meetingTime'] == null ? undefined : json['meetingTime'],
    description: json['description'] == null ? undefined : json['description'],
    qr: json['qr'] == null ? undefined : json['qr'],
    participants: json['participants'] == null ? undefined : json['participants'],
  }
}

export function ActivityToJSON(json: any): Activity {
  return ActivityToJSONTyped(json, false)
}

export function ActivityToJSONTyped(
  value?: Activity | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    activityId: value['activityId'],
    user: SimpleUserToJSON(value['user']),
    date: value['date'] == null ? undefined : value['date'].toISOString().substring(0, 10),
    meetingPlace: value['meetingPlace'],
    activityType: value['activityType'],
    capacity: value['capacity'],
    meetingTime: value['meetingTime'],
    description: value['description'],
    qr: value['qr'],
    participants: value['participants'],
  }
}
