/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ad
 */
export interface Ad {
    /**
     * 
     * @type {string}
     * @memberof Ad
     */
    adId?: string;
    /**
     * 
     * @type {string}
     * @memberof Ad
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof Ad
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof Ad
     */
    info?: string;
    /**
     * 
     * @type {string}
     * @memberof Ad
     */
    code?: string;
    /**
     * 
     * @type {Date}
     * @memberof Ad
     */
    dateFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Ad
     */
    dateUntil?: Date;
}

/**
 * Check if a given object implements the Ad interface.
 */
export function instanceOfAd(value: object): value is Ad {
    return true;
}

export function AdFromJSON(json: any): Ad {
    return AdFromJSONTyped(json, false);
}

export function AdFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ad {
    if (json == null) {
        return json;
    }
    return {
        
        'adId': json['adId'] == null ? undefined : json['adId'],
        'link': json['link'] == null ? undefined : json['link'],
        'image': json['image'] == null ? undefined : json['image'],
        'info': json['info'] == null ? undefined : json['info'],
        'code': json['code'] == null ? undefined : json['code'],
        'dateFrom': json['dateFrom'] == null ? undefined : (new Date(json['dateFrom'])),
        'dateUntil': json['dateUntil'] == null ? undefined : (new Date(json['dateUntil'])),
    };
}

export function AdToJSON(json: any): Ad {
    return AdToJSONTyped(json, false);
}

export function AdToJSONTyped(value?: Ad | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adId': value['adId'],
        'link': value['link'],
        'image': value['image'],
        'info': value['info'],
        'code': value['code'],
        'dateFrom': value['dateFrom'] == null ? undefined : ((value['dateFrom']).toISOString().substring(0,10)),
        'dateUntil': value['dateUntil'] == null ? undefined : ((value['dateUntil']).toISOString().substring(0,10)),
    };
}

