/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdLog
 */
export interface AdLog {
    /**
     * 
     * @type {string}
     * @memberof AdLog
     */
    adId?: string;
    /**
     * 
     * @type {number}
     * @memberof AdLog
     */
    userId?: number;
}

/**
 * Check if a given object implements the AdLog interface.
 */
export function instanceOfAdLog(value: object): value is AdLog {
    return true;
}

export function AdLogFromJSON(json: any): AdLog {
    return AdLogFromJSONTyped(json, false);
}

export function AdLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdLog {
    if (json == null) {
        return json;
    }
    return {
        
        'adId': json['adId'] == null ? undefined : json['adId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function AdLogToJSON(json: any): AdLog {
    return AdLogToJSONTyped(json, false);
}

export function AdLogToJSONTyped(value?: AdLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adId': value['adId'],
        'userId': value['userId'],
    };
}

