/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Article
 */
export interface Article {
  /**
   *
   * @type {number}
   * @memberof Article
   */
  articleId?: number
  /**
   *
   * @type {number}
   * @memberof Article
   */
  articleType?: number
  /**
   *
   * @type {string}
   * @memberof Article
   */
  organizer?: string
  /**
   *
   * @type {string}
   * @memberof Article
   */
  location?: string
  /**
   *
   * @type {string}
   * @memberof Article
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof Article
   */
  description?: string
  /**
   *
   * @type {Date}
   * @memberof Article
   */
  articleDate?: Date
  /**
   *
   * @type {string}
   * @memberof Article
   */
  image?: string
  /**
   *
   * @type {string}
   * @memberof Article
   */
  price?: string
  /**
   *
   * @type {string}
   * @memberof Article
   */
  link?: string
  /**
   *
   * @type {string}
   * @memberof Article
   */
  instagram?: string
  /**
   *
   * @type {string}
   * @memberof Article
   */
  twitter?: string
  /**
   *
   * @type {string}
   * @memberof Article
   */
  tiktok?: string
  /**
   *
   * @type {string}
   * @memberof Article
   */
  facebook?: string
  /**
   *
   * @type {string}
   * @memberof Article
   */
  createdBy?: string
}

/**
 * Check if a given object implements the Article interface.
 */
export function instanceOfArticle(value: object): value is Article {
  return true
}

export function ArticleFromJSON(json: any): Article {
  return ArticleFromJSONTyped(json, false)
}

export function ArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Article {
  if (json == null) {
    return json
  }
  return {
    articleId: json['articleId'] == null ? undefined : json['articleId'],
    articleType: json['articleType'] == null ? undefined : json['articleType'],
    organizer: json['organizer'] == null ? undefined : json['organizer'],
    location: json['location'] == null ? undefined : json['location'],
    title: json['title'] == null ? undefined : json['title'],
    description: json['description'] == null ? undefined : json['description'],
    articleDate: json['articleDate'] == null ? undefined : new Date(json['articleDate']),
    image: json['image'] == null ? undefined : json['image'],
    price: json['price'] == null ? undefined : json['price'],
    link: json['link'] == null ? undefined : json['link'],
    instagram: json['instagram'] == null ? undefined : json['instagram'],
    twitter: json['twitter'] == null ? undefined : json['twitter'],
    tiktok: json['tiktok'] == null ? undefined : json['tiktok'],
    facebook: json['facebook'] == null ? undefined : json['facebook'],
    createdBy: json['createdBy'] == null ? undefined : json['createdBy'],
  }
}

export function ArticleToJSON(json: any): Article {
  return ArticleToJSONTyped(json, false)
}

export function ArticleToJSONTyped(
  value?: Article | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    articleId: value['articleId'],
    articleType: value['articleType'],
    organizer: value['organizer'],
    location: value['location'],
    title: value['title'],
    description: value['description'],
    articleDate: value['articleDate'] == null ? undefined : value['articleDate'].toISOString(),
    image: value['image'],
    price: value['price'],
    link: value['link'],
    instagram: value['instagram'],
    twitter: value['twitter'],
    tiktok: value['tiktok'],
    facebook: value['facebook'],
    createdBy: value['createdBy'],
  }
}
