/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CanyonProhibition
 */
export interface CanyonProhibition {
  /**
   *
   * @type {number}
   * @memberof CanyonProhibition
   */
  canyonProhibitionId?: number
  /**
   *
   * @type {number}
   * @memberof CanyonProhibition
   */
  canyonId?: number
  /**
   *
   * @type {string}
   * @memberof CanyonProhibition
   */
  description?: string
}

/**
 * Check if a given object implements the CanyonProhibition interface.
 */
export function instanceOfCanyonProhibition(value: object): value is CanyonProhibition {
  return true
}

export function CanyonProhibitionFromJSON(json: any): CanyonProhibition {
  return CanyonProhibitionFromJSONTyped(json, false)
}

export function CanyonProhibitionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CanyonProhibition {
  if (json == null) {
    return json
  }
  return {
    canyonProhibitionId:
      json['canyonProhibitionId'] == null ? undefined : json['canyonProhibitionId'],
    canyonId: json['canyonId'] == null ? undefined : json['canyonId'],
    description: json['description'] == null ? undefined : json['description'],
  }
}

export function CanyonProhibitionToJSON(json: any): CanyonProhibition {
  return CanyonProhibitionToJSONTyped(json, false)
}

export function CanyonProhibitionToJSONTyped(
  value?: CanyonProhibition | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    canyonProhibitionId: value['canyonProhibitionId'],
    canyonId: value['canyonId'],
    description: value['description'],
  }
}
