/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CanyonLocation
 */
export interface CanyonLocation {
    /**
     * 
     * @type {number}
     * @memberof CanyonLocation
     */
    canyonId?: number;
    /**
     * 
     * @type {string}
     * @memberof CanyonLocation
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof CanyonLocation
     */
    population?: string;
    /**
     * 
     * @type {string}
     * @memberof CanyonLocation
     */
    latitud?: string;
    /**
     * 
     * @type {string}
     * @memberof CanyonLocation
     */
    longitud?: string;
    /**
     * 
     * @type {string}
     * @memberof CanyonLocation
     */
    zone?: string;
}

/**
 * Check if a given object implements the CanyonLocation interface.
 */
export function instanceOfCanyonLocation(value: object): value is CanyonLocation {
    return true;
}

export function CanyonLocationFromJSON(json: any): CanyonLocation {
    return CanyonLocationFromJSONTyped(json, false);
}

export function CanyonLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CanyonLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'canyonId': json['canyonId'] == null ? undefined : json['canyonId'],
        'country': json['country'] == null ? undefined : json['country'],
        'population': json['population'] == null ? undefined : json['population'],
        'latitud': json['latitud'] == null ? undefined : json['latitud'],
        'longitud': json['longitud'] == null ? undefined : json['longitud'],
        'zone': json['zone'] == null ? undefined : json['zone'],
    };
}

export function CanyonLocationToJSON(json: any): CanyonLocation {
    return CanyonLocationToJSONTyped(json, false);
}

export function CanyonLocationToJSONTyped(value?: CanyonLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'canyonId': value['canyonId'],
        'country': value['country'],
        'population': value['population'],
        'latitud': value['latitud'],
        'longitud': value['longitud'],
        'zone': value['zone'],
    };
}

