/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { SimpleUser } from './SimpleUser'
import {
  SimpleUserFromJSON,
  SimpleUserFromJSONTyped,
  SimpleUserToJSON,
  SimpleUserToJSONTyped,
} from './SimpleUser'
import type { SimpleCanyon } from './SimpleCanyon'
import {
  SimpleCanyonFromJSON,
  SimpleCanyonFromJSONTyped,
  SimpleCanyonToJSON,
  SimpleCanyonToJSONTyped,
} from './SimpleCanyon'

/**
 *
 * @export
 * @interface CanyonReviewResponse
 */
export interface CanyonReviewResponse {
  /**
   *
   * @type {number}
   * @memberof CanyonReviewResponse
   */
  canyonReviewId?: number
  /**
   *
   * @type {SimpleCanyon}
   * @memberof CanyonReviewResponse
   */
  canyon?: SimpleCanyon
  /**
   *
   * @type {SimpleUser}
   * @memberof CanyonReviewResponse
   */
  user?: SimpleUser
  /**
   *
   * @type {Date}
   * @memberof CanyonReviewResponse
   */
  date?: Date
  /**
   *
   * @type {number}
   * @memberof CanyonReviewResponse
   */
  duration?: number
  /**
   *
   * @type {boolean}
   * @memberof CanyonReviewResponse
   */
  combinedCar?: boolean
  /**
   *
   * @type {number}
   * @memberof CanyonReviewResponse
   */
  caudal?: number
  /**
   *
   * @type {string}
   * @memberof CanyonReviewResponse
   */
  description?: string
  /**
   *
   * @type {Array<SimpleUser>}
   * @memberof CanyonReviewResponse
   */
  users?: Array<SimpleUser>
  /**
   *
   * @type {string}
   * @memberof CanyonReviewResponse
   */
  qr?: string
}

/**
 * Check if a given object implements the CanyonReviewResponse interface.
 */
export function instanceOfCanyonReviewResponse(value: object): value is CanyonReviewResponse {
  return true
}

export function CanyonReviewResponseFromJSON(json: any): CanyonReviewResponse {
  return CanyonReviewResponseFromJSONTyped(json, false)
}

export function CanyonReviewResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CanyonReviewResponse {
  if (json == null) {
    return json
  }
  return {
    canyonReviewId: json['canyonReviewId'] == null ? undefined : json['canyonReviewId'],
    canyon: json['canyon'] == null ? undefined : SimpleCanyonFromJSON(json['canyon']),
    user: json['user'] == null ? undefined : SimpleUserFromJSON(json['user']),
    date: json['date'] == null ? undefined : new Date(json['date']),
    duration: json['duration'] == null ? undefined : json['duration'],
    combinedCar: json['combinedCar'] == null ? undefined : json['combinedCar'],
    caudal: json['caudal'] == null ? undefined : json['caudal'],
    description: json['description'] == null ? undefined : json['description'],
    users:
      json['users'] == null ? undefined : (json['users'] as Array<any>).map(SimpleUserFromJSON),
    qr: json['qr'] == null ? undefined : json['qr'],
  }
}

export function CanyonReviewResponseToJSON(json: any): CanyonReviewResponse {
  return CanyonReviewResponseToJSONTyped(json, false)
}

export function CanyonReviewResponseToJSONTyped(
  value?: CanyonReviewResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    canyonReviewId: value['canyonReviewId'],
    canyon: SimpleCanyonToJSON(value['canyon']),
    user: SimpleUserToJSON(value['user']),
    date: value['date'] == null ? undefined : value['date'].toISOString().substring(0, 10),
    duration: value['duration'],
    combinedCar: value['combinedCar'],
    caudal: value['caudal'],
    description: value['description'],
    users:
      value['users'] == null ? undefined : (value['users'] as Array<any>).map(SimpleUserToJSON),
    qr: value['qr'],
  }
}
