/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CanyonDifficulty
 */
export interface CanyonDifficulty {
    /**
     * 
     * @type {number}
     * @memberof CanyonDifficulty
     */
    canyonId?: number;
    /**
     * 
     * @type {string}
     * @memberof CanyonDifficulty
     */
    difficultyDesc?: string;
}

/**
 * Check if a given object implements the CanyonDifficulty interface.
 */
export function instanceOfCanyonDifficulty(value: object): value is CanyonDifficulty {
    return true;
}

export function CanyonDifficultyFromJSON(json: any): CanyonDifficulty {
    return CanyonDifficultyFromJSONTyped(json, false);
}

export function CanyonDifficultyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CanyonDifficulty {
    if (json == null) {
        return json;
    }
    return {
        
        'canyonId': json['canyonId'] == null ? undefined : json['canyonId'],
        'difficultyDesc': json['difficultyDesc'] == null ? undefined : json['difficultyDesc'],
    };
}

export function CanyonDifficultyToJSON(json: any): CanyonDifficulty {
    return CanyonDifficultyToJSONTyped(json, false);
}

export function CanyonDifficultyToJSONTyped(value?: CanyonDifficulty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'canyonId': value['canyonId'],
        'difficultyDesc': value['difficultyDesc'],
    };
}

