/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { ActivityType } from './ActivityType'
import {
  ActivityTypeFromJSON,
  ActivityTypeFromJSONTyped,
  ActivityTypeToJSON,
  ActivityTypeToJSONTyped,
} from './ActivityType'

/**
 *
 * @export
 * @interface MessageIn
 */
export interface MessageIn {
  /**
   *
   * @type {number}
   * @memberof MessageIn
   */
  messageId?: number
  /**
   *
   * @type {number}
   * @memberof MessageIn
   */
  placeId?: number
  /**
   *
   * @type {string}
   * @memberof MessageIn
   */
  message?: string
  /**
   *
   * @type {Date}
   * @memberof MessageIn
   */
  date?: Date
  /**
   *
   * @type {number}
   * @memberof MessageIn
   */
  flow?: number
  /**
   *
   * @type {number}
   * @memberof MessageIn
   */
  temperature?: number
  /**
   *
   * @type {ActivityType}
   * @memberof MessageIn
   */
  typePlace?: ActivityType
}

/**
 * Check if a given object implements the MessageIn interface.
 */
export function instanceOfMessageIn(value: object): value is MessageIn {
  return true
}

export function MessageInFromJSON(json: any): MessageIn {
  return MessageInFromJSONTyped(json, false)
}

export function MessageInFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageIn {
  if (json == null) {
    return json
  }
  return {
    messageId: json['messageId'] == null ? undefined : json['messageId'],
    placeId: json['placeId'] == null ? undefined : json['placeId'],
    message: json['message'] == null ? undefined : json['message'],
    date: json['date'] == null ? undefined : new Date(json['date']),
    flow: json['flow'] == null ? undefined : json['flow'],
    temperature: json['temperature'] == null ? undefined : json['temperature'],
    typePlace: json['typePlace'] == null ? undefined : ActivityTypeFromJSON(json['typePlace']),
  }
}

export function MessageInToJSON(json: any): MessageIn {
  return MessageInToJSONTyped(json, false)
}

export function MessageInToJSONTyped(
  value?: MessageIn | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    messageId: value['messageId'],
    placeId: value['placeId'],
    message: value['message'],
    date: value['date'] == null ? undefined : value['date'].toISOString().substring(0, 10),
    flow: value['flow'],
    temperature: value['temperature'],
    typePlace: ActivityTypeToJSON(value['typePlace']),
  }
}
