/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { SimpleUser } from './SimpleUser'
import {
  SimpleUserFromJSON,
  SimpleUserFromJSONTyped,
  SimpleUserToJSON,
  SimpleUserToJSONTyped,
} from './SimpleUser'

/**
 *
 * @export
 * @interface SimpleActivity
 */
export interface SimpleActivity {
  /**
   *
   * @type {number}
   * @memberof SimpleActivity
   */
  activityId?: number
  /**
   *
   * @type {SimpleUser}
   * @memberof SimpleActivity
   */
  user?: SimpleUser
  /**
   *
   * @type {Date}
   * @memberof SimpleActivity
   */
  date?: Date
  /**
   *
   * @type {string}
   * @memberof SimpleActivity
   */
  meetingPlace?: string
  /**
   *
   * @type {string}
   * @memberof SimpleActivity
   */
  activityType?: string
}

/**
 * Check if a given object implements the SimpleActivity interface.
 */
export function instanceOfSimpleActivity(value: object): value is SimpleActivity {
  return true
}

export function SimpleActivityFromJSON(json: any): SimpleActivity {
  return SimpleActivityFromJSONTyped(json, false)
}

export function SimpleActivityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SimpleActivity {
  if (json == null) {
    return json
  }
  return {
    activityId: json['activityId'] == null ? undefined : json['activityId'],
    user: json['user'] == null ? undefined : SimpleUserFromJSON(json['user']),
    date: json['date'] == null ? undefined : new Date(json['date']),
    meetingPlace: json['meetingPlace'] == null ? undefined : json['meetingPlace'],
    activityType: json['activityType'] == null ? undefined : json['activityType'],
  }
}

export function SimpleActivityToJSON(json: any): SimpleActivity {
  return SimpleActivityToJSONTyped(json, false)
}

export function SimpleActivityToJSONTyped(
  value?: SimpleActivity | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    activityId: value['activityId'],
    user: SimpleUserToJSON(value['user']),
    date: value['date'] == null ? undefined : value['date'].toISOString().substring(0, 10),
    meetingPlace: value['meetingPlace'],
    activityType: value['activityType'],
  }
}
