/* tslint:disable */
/* eslint-disable */
/**
 * Swagger CanyoningApp - OpenAPI 3.0
 * Swagger of canyoning app
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: delgadofernandez.luis@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UpdatePasswordRequest
 */
export interface UpdatePasswordRequest {
  /**
   *
   * @type {string}
   * @memberof UpdatePasswordRequest
   */
  password?: string
}

/**
 * Check if a given object implements the UpdatePasswordRequest interface.
 */
export function instanceOfUpdatePasswordRequest(value: object): value is UpdatePasswordRequest {
  return true
}

export function UpdatePasswordRequestFromJSON(json: any): UpdatePasswordRequest {
  return UpdatePasswordRequestFromJSONTyped(json, false)
}

export function UpdatePasswordRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdatePasswordRequest {
  if (json == null) {
    return json
  }
  return {
    password: json['password'] == null ? undefined : json['password'],
  }
}

export function UpdatePasswordRequestToJSON(json: any): UpdatePasswordRequest {
  return UpdatePasswordRequestToJSONTyped(json, false)
}

export function UpdatePasswordRequestToJSONTyped(
  value?: UpdatePasswordRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    password: value['password'],
  }
}
